### PR TITLE
Local Storage Utility (support encode and decode)

### PR DESCRIPTION
**Pull request by marville001**
Added Local Storage Utility (support encode and decode) snippet (typescript)

image

image

### CODE REVIEW

**Comment by GreenMan36** [comment]
If you strip the types it should be fine as far as I can read.
Perhaps you wish to add Typescript instead?

**Comment by Mathys-Gasnier** [comment]
Hey, thanks for your contribution to the repo.

Snippets to get, set and clear the localstorage already exists, it's true that putting them in a class is a new snippet, but I don't think it fits the scope of the project to put multiple snippets into one like this.

Let's get feedback from other on this topic.

**Comment by Ashish-simpleCoder** [comment]
I think, snippets should be simple to understand and generalized.

Adding encoding and decoding is very specific scenario and few people will be able understand it.

And we should prefer Functional programming instead of class syntax.

And we can modify the existing snippet if want to add additional features.

**Comment by Axorax** [comment]
Personally, I have no use for this snippet. You can already do each of the actions with one line of code. And the encoding and decoding is just base64. New coder's might think it's making their data secure but it's just making it harder to read and nothing else.

**Comment by Mathys-Gasnier** [comment]
Yeah, we are all on the same page, so i'm closing this PR.

**Pull request closed without merging**
