### PR TITLE
Added string split snippet in CPP

### PR DESCRIPTION
**Pull request by saminjay**
Added a new snippet, to split a string in CPP

### CODE REVIEW

**Review by Mathys-Gasnier — COMMENTED** [review]
Could you prehaps add includes to the snippets ?
It would allow users to see what is used in your snippet even before using it !

**Comment by saminjay** [comment]
@Mathys-Gasnier Done.

Should I also add imports to the previous CPP snippet?
It also needs a `using namespace std`.

**Comment by Mathys-Gasnier** [comment]
I think yeah adding includes to other example is a good thing...
But not `using namespace std` it's not a good practice to use it, it can introduce name conflict among other things

**Comment by saminjay** [comment]
Yes, it is a bad practice. That's why I didn't use it in my snippet but the other snippet doesn't include `std::`. If I am fixing that, I would either have to add `std::` in the snippet or add `using namespace std;`. Not sure which one @dostonnabotov would prefer.

**Comment by dostonnabotov** [comment]
@saminjay and @Mathys-Gasnier Thank you for taking your time to review the snippet before submitting it. I'm not very familiar with C++, so I can't help you with this one. You can decide yourselves on which one to implement.

**Comment by saminjay** [comment]
@Mathys-Gasnier @dostonnabotov Done.
I've added the namespace scope operator `std::` and `includes`.

**Review by Mathys-Gasnier — APPROVED** [review]
Great work

**Pull request merged**
