### PR TITLE
Add snippets for Javascript and C

### PR DESCRIPTION
**Pull request by 0xHouss**
# Description

Added a sleep utility function for javascript
Added the "javascript" tag to some snippets for more consistency between the snippets
Added the C programming Language
Added the Basics category in C with a hello world snippet
Added the Mathematical Functions category in C with a factorial and power snippet

## Type of Change

- [x] ✨ New snippet
- [x] 🛠 Improvement to an existing snippet
- [ ] 🐞 Bug fix
- [ ] 📖 Documentation update
- [x] 🔧 Other (please describe): Adds the C programming language.

## Checklist

- [x] I have tested my code and verified it works as expected.
- [x] My code follows the style and contribution guidelines of this project.
- [x] Comments are added where necessary for clarity.
- [x] Documentation has been updated (if applicable).
- [x] There are no new warnings or errors from my changes.

## Related Issues

Closes #

## Screenshots (Optional)

<details> 
<summary>Click to view screenshots</summary> 

</details>

### CODE REVIEW

**Review by Axorax — CHANGES_REQUESTED** [review]
Maybe separate it into different PRs based on the language to make reviewing easier.

image

**Review by Mathys-Gasnier — APPROVED** [review]

**Comment by Mathys-Gasnier** [comment]
Since the changes look good, and the javascript edits are mostly formating issues, i'm going to let this one pass, but please for your futur contributions, separate edits into a PR per language edited.

**Comment by 0xHouss** [comment]
Okay, i didn't know i had to separate them, also i'm new with contributing so i don't really know how pull requests, forking and all this works. Thanks anyway !

**Comment by Axorax** [comment]
> Okay, i didn't know i had to separate them, also i'm new with contributing so i don't really know how pull requests, forking and all this works. Thanks anyway !

U can create multiple branches for different PRs. I learned it just today as well lol

**Pull request merged**
