### PR TITLE
Added a CSS reset snippet

### PR DESCRIPTION
**Pull request by AmeerMoustafa**
Added a simple CSS reset snippet. Something I use in almost every project.

### CODE REVIEW

**Comment by dostonnabotov** [comment]
Hey, there! 👋 Thanks for the contribution

**Comment by AmeerMoustafa** [comment]
@dostonnabotov No worries, it's a great idea. I am considering adding React and Express snippets. What do you think?

**Comment by dostonnabotov** [comment]
@AmeerMoustafa Of course. I'm thinking about including frameworks in current languages in the category part first. As snippets grow, we will then move them to a different file. Let me know your thoughts.

**Comment by AmeerMoustafa** [comment]
@dostonnabotov Sounds good, I'll add a React one right now. Even though I think moving them as a sub-category of Javascript from the get go would be a good idea.

**Pull request merged**
