### PR TITLE
Add some responsive breakpionts in CSS

### PR DESCRIPTION
**Pull request by kruimol**
To create a multi platform website you need breakpoints for varius platforms. 
So I added Responsive design, with: phone, tablet and desktop

### CODE REVIEW

**Review by Mathys-Gasnier — COMMENTED** [review]
Are the `Desktop extra large` and `bige` really necessary ?

**Comment by kruimol** [comment]
> Are the `Desktop extra large` and `bige` really necessary ?

It may be necessary in some cases,
If you don't need the extra large and big ones, remove them, it's still a 'template'/snipid
In my case I have a 2.7K screen, so it may be useful.

**Comment by Mathys-Gasnier** [comment]
I think snippet should show the functionning of a feature, and for media queries i think just showing the user how it works (explaining that it only applies if screen size > an amount, etc) is the goal, more than giving the user a list of media queries without explaination

**Comment by kruimol** [comment]
> I think snippet should show the functionning of a feature, and for media queries i think just showing the user how it works (explaining that it only applies if screen size > an amount, etc) is the goal, more than giving the user a list of media queries without explaination

That's true, 
but sometimes I don't know what the correct sizes/breakpoints are, 
so I thought it would be helpful to include the ''standard' breakpoints.

**Comment by dostonnabotov** [comment]
@kruimol, thank you for the contribution. 🙌

I like the idea of adding responsive design. Regarding the breakpoints, we can move them to SCSS maps to show in an organized way. Something like this:

```scss
// values needs to be updated here as well
$breakpoints: (
  sm: 30em,
  md: 50em,
  lg: 75em,
);
``` 

Add a mixin to access those breakpoints from maps with `@media`, and now you have a useful code snippet that people can just copy and use in their code.

```scss
// media query
@mixin mq($key) {
  $size: map-get($breakpoints, $key);

  @if ($size) {
    @media (width > $size) {
      @content;
    }
  } @else {
    @error '`#{$key}` does not exist in the $breakpoints';
  }
}
```

Let me know what you think.

**Comment by dostonnabotov** [comment]
And, we still need breakpoints in CSS as well. Because some developers aren't familiar with SCSS yet. So, adding a code snippet for _common_ breakpoints would help them a lot.

I think `margin` might be unnecessary, just mentioning very common 3-4 breakpoints might be enough to give an idea.

I'm open to listening your approach on this one as well.

**Comment by kruimol** [comment]
> And, we still need breakpoints in CSS as well. Because some developers aren't familiar with SCSS yet. So, adding a code snippet for _common_ breakpoints would help them a lot.
> 
> I think `margin` might be unnecessary, just mentioning very common 3-4 breakpoints might be enough to give an idea.
> 
> I'm open to listening your approach on this one as well.

Yes that was my intention too, I'm not that familiar with scss myself.
That's why I thought I'd add the @media breakpoints.
The margins are just an example of how to use them.
Like in this example that the margin increases as the screen gets bigger.
And if possible, leave the big ones as they are, because some screens it can be more useful for those big ones.

**Pull request merged**
